# Activation Functions

In [4]:
import torch as torch
import torch.nn as nn
import numpy as np

# Sigmoid
Advantages

    output range is (0,1)
    converts large negative toward 0 and large positive toward 1
    returns 0.5 for input 0 Pros
    it is nonlinear in nature
    the output is between 0 and 1
    it has smooth gradient
    good for classification

Disadvantages

    Y changes very less at either end.
    vanishing gradient problem
    computationally expensive
    non zero centered thus optimization is harder


In [37]:
m = nn.Sigmoid()
input = torch.randn(2)
output = m(input)
print(input)
print(output)

tensor([-0.0747, -0.3188])
tensor([0.4813, 0.4210])


# Tanh
Features

    output values in the range of (-1,1)

Pros

    The main difference with sigmoid is-- it is zero centered; thus optimization is easier than sigmoid
    stronger gradient than sigmoid

Cons

    It also has vanishing gradient issue


In [43]:
m = nn.Tanh()
input = torch.randn(2)
output = m(input)
print(input)
print(output)

tensor([ 1.9897, -2.8444])
tensor([ 0.9633, -0.9933])


# ReLU 
#Relu is an activation function that returns 0 for negative numbers
#Advantages include faster calculation and  reduced chance of vanishing gradient
#Disadvantage is that you could have several nodes always returning zero for negative numbers (dying ReLU)
#and can only be used in hidden layer

In [6]:


#initialize our neural network
def __init__(self):
        super(Net, self).__init__()
        self.model=Sequential(

         #hidden Layer 1   
         nn.Linear(4,5),
          nn.ReLU(),

          #hidden layer 2
          nn.Linear(5, 3),
          nn.ReLU(),

          
          nn.Linear(3, 1)

        )


In [24]:
#example, create a tensor filled with 2 random numbers 
m = nn.ReLU()
input = torch.randn(2)
output = m(input)
print('Testing ReLU with random numbers')
print('Initial input to ReLU: ')
print(input)
print('Initial output of ReLU: ')
print(output)

print('------------')
#Scenario with negative inputs
print('Testing ReLU with negative numbers')
m = nn.ReLU()

input = torch.randn(2).unsqueeze(0)
print('Input to ReLU after unsqueeze (adds dimension): ')
print(input)

#add an extra dimension with negative of input
output = torch.cat((m(input),m(-input)))
print("Output of ReLU with negative numbered inputs:")
print(output)

Testing ReLU with random numbers
Initial input to ReLU: 
tensor([-0.8611,  0.6728])
Initial output of ReLU: 
tensor([0.0000, 0.6728])
------------
Testing ReLU with negative numbers
Input to ReLU after unsqueeze (adds dimension): 
tensor([[-0.7964, -0.0486]])
Output of ReLU with negative numbered inputs:
tensor([[0.0000, 0.0000],
        [0.7964, 0.0486]])


# LeakyReLU
LeakyReLU allows for small negative numbers, preventing dying ReLU problem
Convergence is faster

In [31]:
m = nn.LeakyReLU()
input = torch.randn(2)
output = m(input)
print(input)
print(output)

tensor([-1.8515,  0.6407])
tensor([-0.0185,  0.6407])


## SoftMax
SoftMax function can be used in output layer to yield probabilities for classification problems (used in training)
ArgMax can be used after training to yield 1 or 0 values in classification problems


In [5]:

def softmax(xs):
    return np.exp(xs) / sum(np.exp(xs))

xs = np.array([-1, 0, 3, 5])
print(softmax(xs)) # [0.0021657, 0.00588697, 0.11824302, 0.87370431]

[0.0021657  0.00588697 0.11824302 0.87370431]
