# Pytorch Tensors

In [10]:
import torch

#create simple tensor with one dimension of value 1.5
x= torch.tensor(1.5)

#arithmetic operation, y becomes type tensor
y=x*3
print(y)
print(type(y))

tensor(4.5000)
<class 'torch.Tensor'>


In [11]:
#create tensor of dimension 2,4 with zeros
z=torch.zeros([2, 4], dtype=torch.int32)

#create tensor of dimension 2,3,2 with 1s
o=torch.ones([2,3,2], dtype=torch.float64)

#you can think of tensor dimensions starting from back to front, columns -> rows -> rows
print(z)
print(o)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]], dtype=torch.float64)


In [12]:
#you can convert an numpy array to a tensor
import numpy as np
y=torch.tensor(np.array([[1,2,3],[4,5,6]]))
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


# Use of autograd

In [13]:
import numpy as np
#when you create a tensor with requires_grad = true, all operations are tracked
#y = x^2 + 3x
x=torch.tensor(2.0, requires_grad=True)
y=x**2+3*x
print('x :', x)
print('y. :', y)

x : tensor(2., requires_grad=True)
y. : tensor(10., grad_fn=<AddBackward0>)


In [14]:
#dy/dx(x^2+3x) = 2x+3
#dy/dx at x=2.0 = 7
#Lets make a new calculation using y (y currently =10)
z=y**2 +y
print(z)

tensor(110., grad_fn=<AddBackward0>)


In [15]:
#Computes the gradient of current tensor w.r.t. graph leaves
#This step calculates the derivative of z=y^2+y, where y=x^2+3x, or z=(x^2+3x)^2+(x^2+3x)
z.backward(retain_graph=True)

In [16]:
#show the gradient computed for x
#this will be the derivate of (x^2+3x)^2+(x^2+3x) which is = 4x^3+18x^2+20x+3, where x=2
x.grad

tensor(147.)

In [8]:
#Computes the gradient of current tensor w.r.t. graph leaves
#This will use gradient accumulation so result will be 147 + y
#remember that y = 7 at x=2

y.backward()
x.grad

tensor(154.)

In [17]:
#if we reset the graph before performing the backwards computation on y, we get original y value at x=2
#To test this, you need to run the full code again but skip the previous code block 
x.grad.zero_()
y.backward()
x.grad

tensor(7.)